### ISSUE TITLE
Create a separate table/tables with sensor coordinates information.

### ISSUE THREAD

**Issue by time-trader** [aerosense-ai/data-gateway#106]
### Use Case

Currently sensor coordinates are stored in the "configuration" table. The metadata for each configuration already contains ids for other data such as blade id, wind turbine id. Lets keep the configuration table static (i.e. only add row to it as new configurations are used).

Meanwhile, Information about blade, or sensor positions can change as we go along. For example we don't know the exact position of sensors when we install the sensors, but as we process photogrammetry data we can edit the position table/tables.

**Comment by cortadocodes** [comment]
Thanks for raising. When do you need this completed by?

**Comment by time-trader** [comment]
Not urgent. More of a conceptual note. We  are probably going to add this data manually in colab notebooks for now.

**Comment by cortadocodes** [comment]
Also: have a sensor conversion constants table

**Comment by cortadocodes** [comment]
@thclark what do you think about this?

**Comment by time-trader** [comment]
@tommasopolonelli, rightfully noted that as we start to do more measurement campaigns and are about to install more nodes, properly storing this metadata and integrating it with aerosense-tools API became a more pressing issue.

@thclark  any input on this, or should we go ahead and do this?

**Comment by cortadocodes** [comment]
To do:
- [x] Create table with `coordinates_table.json` column names
- [x] Store the other schemas in `strands` (sections and IMU schemas)
- [x] Update `data-gateway` to store an ID for each sensor installation instead of the coordinates. It should do nothing else with coordinates
- [x] Add function to `aerosense-tools` to add coordinates that also validates input coordinates against schema

**Comment by thclark** [comment]
@cortadocodes can I just check that any legacy coordinates that are hard coded now are set up to use the table?

**Comment by cortadocodes** [comment]
I don't think there are any real legacy coordinates, I think only the default values of 0 are in there from before

**Comment by cortadocodes** [comment]
@time-trader am I correct?
