### ISSUE TITLE
Poetry installation prevents tests from running in CI

### ISSUE THREAD

**Issue by thclark** [aerosense-ai/data-gateway#110]
## Bug report

[This windows action](https://github.com/aerosense-ai/data-gateway/actions/runs/3581599824/jobs/6024847653) failed because of a problem with poetry check that we've not seen before.

![Screenshot 2022-12-07 at 09 11 26](https://user-images.githubusercontent.com/7223170/206137058-492c35bc-75df-4593-9695-cc7f4a18d7e7.png)

**Comment by cortadocodes** [comment]
I'm pretty sure I've come across this myself elsewhere. Let me see if I can fix it
