### ISSUE TITLE
Cloud function fails to add sensor data.

### ISSUE THREAD

**Issue by time-trader** [aerosense-ai/data-gateway#116]
### What is the current behavior?
Cloud function will not add sensor data to greta.sensor_data because there is no column named "measurement_campaign_reference" in that table. 

### What is the expected behavior?
I am not sure there is a need to have measurement_campaign_reference column at all in greta.sensor_data,  Including this column makes measurement_campaign table redundant, because it would be simply generated with a query over sensor_data.

**Comment by cortadocodes** [comment]
The `measurement_campaign` column is just the reference for the measurement campaign (not the rest of the data associated with it) and was added to the `sensor_data` table so you're able to tell which data was produced in which measurement campaign.

**Comment by cortadocodes** [comment]
I've just added the new columns to the tables
