### ISSUE TITLE
Installation on Raspberry Pi OS

### ISSUE THREAD

**Issue by time-trader** [aerosense-ai/data-gateway#2]
Following packages are pre-requisites for gateway on Raspbian GNU/Linux 10 (buster):
### RUST:
Using: `sudo apt-get install rustc`, does not cut it. Most recent build is needed:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
### OpenSSL, HDF5, ATLAS:
`sudo apt-get install libssl-dev libhdf5-dev libatlas-base-dev`

This might change for the newly released Raspbian Based on Debian 11 (Bullseye)

**Comment by cortadocodes** [comment]
There are multiple issues here. Could you let me know if each is still a problem with the latest gateway version (soon to be released)? I've removed some unnecessary requirements so this issue may be alleviated to some extent
- Requiring rust
- Requiring `libssl-dev` `libhdf5-dev` `libatlas-base-dev`
- CRC32C warning

@thclark we may need to do a fresh install on a wiped Raspberry Pi to verify each of these

**Comment by cortadocodes** [comment]
### `rust`
I've removed this as a development requirement, but it is still used in the cloud function.

### `google-crc32c`
I can't see a way to make the C extension available in a way that keeps `data-gateway` easily installable without using a docker container. I've resolved to keep using the python implementation for now.

**Comment by cortadocodes** [comment]
After further dependency optimisations, `libhdf5-dev` and `libhdf5-serial` appear to no longer be required. I've tested this by just installing from the `requirements-pi.txt` file on a wiped Raspberry Pi and running the gateway on an empty serial port.
