### ISSUE TITLE
Routine is not executed in the new multiprosseing version

### ISSUE THREAD

**Issue by time-trader** [aerosense-ai/data-gateway#33]
## Bug report

For #30,   f5599ab8c54143189fdf7300087dc011c354eb9b  ,  --routine-file=PATH flag, is not working anymore, and the routine is not read/executed.

**Comment by cortadocodes** [comment]
This should be fixed by the latest commit in #30

**Comment by time-trader** [comment]
Yes! Thank you! 

Also I thought we have a warning if the routine file doesn't exist was it on another branch?

**Comment by cortadocodes** [comment]
I've demoted several log messages down to `debug` level in #30 including that one I think - please could you check the PR to see if you'd like any of them left at `info`?
