### ISSUE TITLE
Persist recieved battery state info to cloud

### ISSUE THREAD

**Issue by time-trader** [aerosense-ai/data-gateway#35]
### Use Case
Save Battery state info packet as a "sensor" data and send it to the cloud.

### Current state.
Battery state info packet currently only outputs to logger

**Comment by time-trader** [comment]
On the second thought, I am not sure this is entirely needed, and it is very much out of place in between the rest of the data.

**Comment by cortadocodes** [comment]
@time-trader shall we close this issue then?
