### ISSUE TITLE
Recompute sensor_time_offset after handles update.

### ISSUE THREAD

**Issue by time-trader** [aerosense-ai/data-gateway#42]
### Use Case

Sensor node internal clock can reset itself, if the sensor node crashes and resets. If such event occurs, sensor_time_offset should be recomputed. 

### Current state

Currently sensor_time_offset is computed only once per gateway session. IF the internal sensor node clock is reset during the gateway operation, and the connection is reestablished, then previously computed offset is no longer correct.

### Proposed solution
When connection is reestablished, the handles are updated, so it is possible to reinitialize sensor_time_offset to None, in this method. This will force time-stamping method to recompute it.

**Comment by time-trader** [comment]
@WeikangKong, @tommasopolonelli since you introduce cross-node synchronization, do you have something like a "master clock"? If so, what is t=0 for that clock?

**Comment by WeikangKong** [comment]
> @WeikangKong, @tommasopolonelli since you introduce cross-node synchronization, do you have something like a "master clock"? If so, what is t=0 for that clock?

t=0 would be around the moment when the base station is turned on.

**Comment by cortadocodes** [comment]
Closed by #25

**Comment by time-trader** [comment]
> > @WeikangKong, @tommasopolonelli since you introduce cross-node synchronization, do you have something like a "master clock"? If so, what is t=0 for that clock?
> 
> t=0 would be around the moment when the base station is turned on.

@WeikangKong  you mean when the bt receiver is plugged in, or the gateway script started?

**Comment by WeikangKong** [comment]
> > > @WeikangKong, @tommasopolonelli since you introduce cross-node synchronization, do you have something like a "master clock"? If so, what is t=0 for that clock?
> > 
> > 
> > t=0 would be around the moment when the base station is turned on.
> 
> @WeikangKong you mean when the bt receiver is plugged in, or the gateway script started?

when the bt receiver is plugged in (power on)

**Comment by time-trader** [comment]
oki thanks.

**Comment by time-trader** [comment]
Sensor_time_offset was not computed correctly for recent tests.

**Comment by cortadocodes** [comment]
I think this is because the offset is reset in the `Reader` process - this attribute value change won't be communicated to the `Parser` process. I'll need to make the attribute process-safe or only update the handles in the `Parser` process.
