### ISSUE TITLE
pyenv local 3.7.0 

### ISSUE THREAD

**Issue by tommasopolonelli** [aerosense-ai/data-gateway#59]
on windows I get a package compatibility issue using the suggested windows package

**Comment by cortadocodes** [comment]
Hi Tommaso, `data-gateway` requires `python>=3.7.1` in [here](https://github.com/aerosense-ai/data-gateway/blob/main/pyproject.toml#L22) 🙏

**Comment by cortadocodes** [comment]
Although also note that we've just found that the inclusive upper limit of the compatible range is `3.9`, not `3.10` as currently stated in the `main` branch.
