### ISSUE TITLE
Test whether using the `pyserial==3.5` "beta" is problematic

### ISSUE THREAD

**Issue by cortadocodes** [aerosense-ai/data-gateway#61]
This is the current version being used and may be causing issues.

**Comment by thclark** [comment]
No longer doing this, so I'm closing down.

**Comment by cortadocodes** [comment]
I think this should still maybe be looked at because version 3.5 is the one we're actually using. We might want to go to version 3.4 [which is the latest non-prerelease version on GitHub](https://github.com/pyserial/pyserial/releases).

**Comment by thclark** [comment]
Oh, that's weird that a ^3.5 will install a beta version. Sigh!
